# https://www.netlifycms.org/docs/configuration-options/
backend:
  name: git-gateway
  repo: stephaniedavidson/portfolio
  branch: master

slug:
  encoding: "ascii"
  clean_accents: true
  sanitize_replacement: "_"

media_folder: static/assets
public_folder: /assets

collections:
  - name: work
    label: Work
    folder: content
    create: true
    media_folder: ""
    public_folder: ""
    fields:
      # - { name: path, label: Path }
      - { name: slug, label: Slug }
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: image, label: "Cover image", widget: image }
      - { name: description, label: Description }
      - { name: body, label: Body, widget: markdown }
