# https://www.netlifycms.org/docs/configuration-options/
backend:
  name: github
  repo: stephaniedavidson/portfolio
  branch: master

slug:
  encoding: "ascii"
  clean_accents: true
  sanitize_replacement: "_"

media_folder: static/assets
public_folder: /assets

collections:
  - name: work
    label: Work
    label_singular: "Work"
    folder: content
    create: true
    # path: "{{custom_slug}}/index"
    path: "{{slug}}/index"
    identifier_field: title
    media_folder: ""
    public_folder: ""
    fields:
      # - { name: custom_slug, label: Slug, widget: string }
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: "tags", label: "Tags", widget: "list" }
      - { name: cover, label: "Cover image", widget: file }
      - { name: body, label: Body, widget: markdown }
