# https://www.netlifycms.org/docs/configuration-options/
backend:
  name: git-gateway
  repo: stephaniedavidson/portfolio
  branch: master

slug:
  encoding: "ascii"
  clean_accents: true
  sanitize_replacement: "_"

media_folder: static/assets
public_folder: /assets

collections:
  - name: work
    label: Work
    label_singular: "Work"
    folder: content
    path: "{{slug}}/index"
    media_folder: ""
    public_folder: ""
    fields:
      - label: Title
        name: title
        widget: string
      - label: "Cover Image"
        name: "image"
        widget: "image"
