backend:
  name: git-gateway
  repo: stephaniedavidson/portfolio
  branch: master

media_folder: static/assets
public_folder: assets

collections:
  - name: work
    label: Work
    folder: content
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: description, label: Description }
      - { name: body, label: Body, widget: markdown }
